package com.example.greatbook.greendao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.example.greatbook.greendao.entity.ContentCommit;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTENT_COMMIT".
*/
public class ContentCommitDao extends AbstractDao<ContentCommit, Long> {

    public static final String TABLENAME = "CONTENT_COMMIT";

    /**
     * Properties of entity ContentCommit.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "proid");
        public final static Property EssayId = new Property(1, long.class, "essayId", false, "ESSAY_ID");
        public final static Property Time = new Property(2, java.util.Date.class, "time", false, "TIME");
        public final static Property CommitTips = new Property(3, String.class, "commitTips", false, "COMMIT_TIPS");
        public final static Property CommitContent = new Property(4, String.class, "commitContent", false, "COMMIT_CONTENT");
        public final static Property OriginContent = new Property(5, String.class, "originContent", false, "ORIGIN_CONTENT");
        public final static Property BelongUserId = new Property(6, String.class, "belongUserId", false, "BELONG_USER_ID");
        public final static Property BelongUserAccount = new Property(7, String.class, "belongUserAccount", false, "BELONG_USER_ACCOUNT");
    };

    private Query<ContentCommit> essay_ContentCommitsQuery;

    public ContentCommitDao(DaoConfig config) {
        super(config);
    }
    
    public ContentCommitDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTENT_COMMIT\" (" + //
                "\"proid\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ESSAY_ID\" INTEGER NOT NULL ," + // 1: essayId
                "\"TIME\" INTEGER," + // 2: time
                "\"COMMIT_TIPS\" TEXT," + // 3: commitTips
                "\"COMMIT_CONTENT\" TEXT," + // 4: commitContent
                "\"ORIGIN_CONTENT\" TEXT," + // 5: originContent
                "\"BELONG_USER_ID\" TEXT," + // 6: belongUserId
                "\"BELONG_USER_ACCOUNT\" TEXT);"); // 7: belongUserAccount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTENT_COMMIT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ContentCommit entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEssayId());
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(3, time.getTime());
        }
 
        String commitTips = entity.getCommitTips();
        if (commitTips != null) {
            stmt.bindString(4, commitTips);
        }
 
        String commitContent = entity.getCommitContent();
        if (commitContent != null) {
            stmt.bindString(5, commitContent);
        }
 
        String originContent = entity.getOriginContent();
        if (originContent != null) {
            stmt.bindString(6, originContent);
        }
 
        String belongUserId = entity.getBelongUserId();
        if (belongUserId != null) {
            stmt.bindString(7, belongUserId);
        }
 
        String belongUserAccount = entity.getBelongUserAccount();
        if (belongUserAccount != null) {
            stmt.bindString(8, belongUserAccount);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ContentCommit entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEssayId());
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(3, time.getTime());
        }
 
        String commitTips = entity.getCommitTips();
        if (commitTips != null) {
            stmt.bindString(4, commitTips);
        }
 
        String commitContent = entity.getCommitContent();
        if (commitContent != null) {
            stmt.bindString(5, commitContent);
        }
 
        String originContent = entity.getOriginContent();
        if (originContent != null) {
            stmt.bindString(6, originContent);
        }
 
        String belongUserId = entity.getBelongUserId();
        if (belongUserId != null) {
            stmt.bindString(7, belongUserId);
        }
 
        String belongUserAccount = entity.getBelongUserAccount();
        if (belongUserAccount != null) {
            stmt.bindString(8, belongUserAccount);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ContentCommit readEntity(Cursor cursor, int offset) {
        ContentCommit entity = new ContentCommit( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // essayId
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // commitTips
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // commitContent
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // originContent
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // belongUserId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // belongUserAccount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ContentCommit entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEssayId(cursor.getLong(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setCommitTips(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCommitContent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setOriginContent(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBelongUserId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBelongUserAccount(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ContentCommit entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ContentCommit entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "contentCommits" to-many relationship of Essay. */
    public List<ContentCommit> _queryEssay_ContentCommits(long essayId) {
        synchronized (this) {
            if (essay_ContentCommitsQuery == null) {
                QueryBuilder<ContentCommit> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.EssayId.eq(null));
                queryBuilder.orderRaw("T.'TIME' DESC");
                essay_ContentCommitsQuery = queryBuilder.build();
            }
        }
        Query<ContentCommit> query = essay_ContentCommitsQuery.forCurrentThread();
        query.setParameter(0, essayId);
        return query.list();
    }

}
