package com.example.greatbook.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greatbook.greendao.entity.LocalGroup;
import com.example.greatbook.greendao.entity.LocalRecord;

import com.example.greatbook.greendao.LocalGroupDao;
import com.example.greatbook.greendao.LocalRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localGroupDaoConfig;
    private final DaoConfig localRecordDaoConfig;

    private final LocalGroupDao localGroupDao;
    private final LocalRecordDao localRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localGroupDaoConfig = daoConfigMap.get(LocalGroupDao.class).clone();
        localGroupDaoConfig.initIdentityScope(type);

        localRecordDaoConfig = daoConfigMap.get(LocalRecordDao.class).clone();
        localRecordDaoConfig.initIdentityScope(type);

        localGroupDao = new LocalGroupDao(localGroupDaoConfig, this);
        localRecordDao = new LocalRecordDao(localRecordDaoConfig, this);

        registerDao(LocalGroup.class, localGroupDao);
        registerDao(LocalRecord.class, localRecordDao);
    }
    
    public void clear() {
        localGroupDaoConfig.getIdentityScope().clear();
        localRecordDaoConfig.getIdentityScope().clear();
    }

    public LocalGroupDao getLocalGroupDao() {
        return localGroupDao;
    }

    public LocalRecordDao getLocalRecordDao() {
        return localRecordDao;
    }

}
