package com.example.greatbook.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.greatbook.greendao.entity.DiarySelf;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DIARY_SELF".
*/
public class DiarySelfDao extends AbstractDao<DiarySelf, Long> {

    public static final String TABLENAME = "DIARY_SELF";

    /**
     * Properties of entity DiarySelf.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Content = new Property(1, String.class, "content", false, "CONTENT");
        public final static Property BelongId = new Property(2, String.class, "belongId", false, "BELONG_ID");
        public final static Property BelongUserAccount = new Property(3, String.class, "belongUserAccount", false, "BELONG_USER_ACCOUNT");
        public final static Property Time = new Property(4, java.util.Date.class, "time", false, "TIME");
    };


    public DiarySelfDao(DaoConfig config) {
        super(config);
    }
    
    public DiarySelfDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DIARY_SELF\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CONTENT\" TEXT," + // 1: content
                "\"BELONG_ID\" TEXT," + // 2: belongId
                "\"BELONG_USER_ACCOUNT\" TEXT," + // 3: belongUserAccount
                "\"TIME\" INTEGER);"); // 4: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DIARY_SELF\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DiarySelf entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
 
        String belongId = entity.getBelongId();
        if (belongId != null) {
            stmt.bindString(3, belongId);
        }
 
        String belongUserAccount = entity.getBelongUserAccount();
        if (belongUserAccount != null) {
            stmt.bindString(4, belongUserAccount);
        }
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(5, time.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DiarySelf entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
 
        String belongId = entity.getBelongId();
        if (belongId != null) {
            stmt.bindString(3, belongId);
        }
 
        String belongUserAccount = entity.getBelongUserAccount();
        if (belongUserAccount != null) {
            stmt.bindString(4, belongUserAccount);
        }
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(5, time.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DiarySelf readEntity(Cursor cursor, int offset) {
        DiarySelf entity = new DiarySelf( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // content
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // belongId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // belongUserAccount
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DiarySelf entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBelongId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBelongUserAccount(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTime(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DiarySelf entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DiarySelf entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
